# coding: utf-8

# flake8: noqa

"""
    API de Gestion de Contenu de Cours

    API REST pour gérer le contenu des cours en ligne, incluant les cours, séances, et l’organisation par module ou par semaine.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cours_api import CoursApi
from swagger_client.api.sances_api import SancesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
