# coding: utf-8

# flake8: noqa
"""
    API de Gestion de Contenu de Cours

    API REST pour gérer le contenu des cours en ligne, incluant les cours, séances, et l’organisation par module ou par semaine.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
